### ISSUE TITLE
Experiencing a few crashes on v1.2.0

### ISSUE THREAD

**Issue by Fironet** [poppeman/Pictus#13]
Since using the new 1.2.0 version I've experienced the two crash dialog messages in a day, although it hasn't been in the middle of viewing images. Unsure what has triggered the crash dialogs, but the last one was after viewing a GIF then closing the window (couldn't reproduce).

Here is the crash dialog error output:

```
Problem signature:
  Problem Event Name:   BEX64
  Application Name: Pictus.exe
  Application Version:  1.2.0.0
  Application Timestamp:    549897ad
  Fault Module Name:    d3d9.dll_unloaded
  Fault Module Version: 6.3.9600.17095
  Fault Module Timestamp:   534b7c88
  Exception Offset: 000000000000d845
  Exception Code:   c0000005
  Exception Data:   0000000000000008
  OS Version:   6.3.9600.2.0.0.256.48
  Locale ID:    3081
  Additional Information 1: d41d
  Additional Information 2: d41d8cd98f00b204e9800998ecf8427e
  Additional Information 3: 0062
  Additional Information 4: 0062b45507e302fa589ecd5b2f81a5b3
```

Using the app currently in portable mode, if that makes any difference.

**Comment by poppeman** [comment]
I managed to reproduce it in a virtual machine, so hopefully I've managed to fix it properly this time. I would appreciate some testing though before I re-release, as I'm not sure exactly what is/was causing the crash.

https://poppeman.se/beta/PictInst.exe
https://poppeman.se/beta/pictus64.zip
https://poppeman.se/beta/pictus32.zip

**Comment by poppeman** [comment]
Managed to reproduce it on some physical machines as well and the fix helped on all of them. Hooray I hope!
