### ISSUE TITLE
Panning breaks when image is rotated

### ISSUE THREAD

**Issue by Fironet** [poppeman/Pictus#23]
Found a little bug where if an image is rotated in Pictus 180 degrees panning with the mouse doesn't function. While when rotated 90 / 270 degrees it only pans in one direction.

**Comment by poppeman** [comment]
I think it broke in 1.2.2, shouldn't take too long to get a new version out.

**Comment by poppeman** [comment]
Everything seems sane now, so I've released 1.2.3 now.

**Comment by Fironet** [comment]
Cheers :)
