### ISSUE TITLE
Strange rendering of certain JPEGs

### ISSUE THREAD

**Issue by Fironet** [poppeman/Pictus#27]
Certain JPEGs display strangely in Pictus. It's rare to come across a JPEG with this issue but reporting it in case the cause can be found.

Side by side comparison (Pictus on left, regular on right):

![example 2 - comparision](https://cloud.githubusercontent.com/assets/6971981/8235489/a41c6436-1625-11e5-8866-7bbd82ebeb42.png)

Example images with the issue:

![example 1](https://cloud.githubusercontent.com/assets/6971981/8235491/a484c7b0-1625-11e5-9459-9c1521c62afc.jpg)
![example 2](https://cloud.githubusercontent.com/assets/6971981/8235492/a48545c8-1625-11e5-9f08-00b8337b2741.jpg)

**Comment by poppeman** [comment]
Those two images are using color profiles/spaces that I've previously not encountered in jpeg files, and thus not been able to test against. Shouldn't be *too* hard to implement the conversion for those.

**Comment by Fironet** [comment]
Yeah, haven't been encountering many like that so it's not something I'm running into regularly.

**Comment by poppeman** [comment]
I'll get basic support for these images in the next big'ish release. For perfect result one might need to process any embedded color profile, but Pictus is not awesome enough for that yet.

**Comment by poppeman** [comment]
Current dev code seems to be fairly functional (although colors can still get off if there's color profiles to consider).
