### ISSUE TITLE
Images stretch momentarily during navigation [v1.3.0]

### ISSUE THREAD

**Issue by Fironet** [poppeman/Pictus#29]
Just updated to v1.3.0 from 1.2.2 and noticed that during navigation the existing image momentarily stretches to the next image's aspect ratio, something that didn't occur in v1.2.2. Captured some GIFs of it below.

v1.2.2:
![1 2 2](https://cloud.githubusercontent.com/assets/6971981/9153528/0da6117a-3ea0-11e5-95f9-cc503756bc65.gif)

v1.3.0:
![1 3](https://cloud.githubusercontent.com/assets/6971981/9153529/0da9cb4e-3ea0-11e5-87bd-bb9f49f4561e.gif)

**Comment by poppeman** [comment]
1.3.0 is cooperating a bit more with the desktop window manager, and if rendering takes too long DWM stretches out the last known window content. Technically it should be a bit faster, but it looks weird and that can therefore make it a net usability loss. I'll see what can be done and revert if there's no good way to mitigate it.

**Comment by poppeman** [comment]
Old behavior restored for 1.3.1 which should be released soon'ish.

**Comment by Fironet** [comment]
Nice!
