### ISSUE TITLE
Window resize fails to scale image after zooming

### ISSUE THREAD

**Issue by Fironet** [poppeman/Pictus#3]
To reproduce set the Resize behavior to 'Reduce only', open an image and zoom out or in, then try resizing the window. The image no longer scales, even if the zoom is reset.

**Comment by poppeman** [comment]
Whoops, totally forgot about this issue. I have tweaked the behavior for 1.5.0. Hopefully nobody will want the old behavior since it was fairly odd. Now Pictus will return to the default zoom mode on the first click if you have zoomed in or out manually, rather than going to full size.
