### ISSUE TITLE
'Fill' set wallpaper option

### ISSUE THREAD

**Issue by Fironet** [poppeman/Pictus#37]
In both OSX and windows there's a 'fill' option when setting images as wallpaper that centers and scales the image to fit the width of the monitor (if the orientation is portrait) or height (if it's landscape).

It's a useful feature and would be nice to see the same option in Pictus, as often images used for desktop backgrounds are either too large or too small for the existing set wallpaper methods in Pictus and 'Fill' is a good all-rounder.

**Comment by poppeman** [comment]
Yeah, the current available options are fairly garbage but they were the only ones available when I actually wrote the feature (sometimes before Windows 7 was released). It seems to be trivial to add support for the new methods, but they might not get added in the next version that should be released somewhat soon.

**Comment by poppeman** [comment]
Fill and fit added for Windows 7+, span for Windows 8+.
