### ISSUE TITLE
Toggle full size/default zoom keyboard hotkey option

### ISSUE THREAD

**Issue by Fironet** [poppeman/Pictus#54]
This useful combined function is available for the mouse controls but appears to be absent from the keyboard hotkey drop-down selection (only the individual functions appear).

Would be nice if it could be added to the keyboard shortcuts, especially handy for those who often control the image viewer mouseless.

**Comment by poppeman** [comment]
Huh, could have sworn I added that! Will fix that in the next feature release (and probably check if I missed any other relevant mouse-only-feature)

**Comment by Fironet** [comment]
Thanks for looking into it.

**Comment by poppeman** [comment]
Added, will appear in next version
