### ISSUE TITLE
Pan to top/bottom, pan by screen hotkey options

### ISSUE THREAD

**Issue by Fironet** [poppeman/Pictus#61]
One of the most frequent type of images I use Pictus to interact with are page designs and screenshots of long pages, and quite a bit of time is spent using the pan keys or mouse to scroll around the image, especially the top.

What would be nice is a keyboard shortcut that could pan to the very top/down of an image, like the Home/Ends key do for web pages for example, and similarly a hotkey to pan by an entire screen in different directions. In that way one key could be pressed for toggling full size and another for panning to the top or end of an image, or by a whole screen up/down/left/right.

**Comment by poppeman** [comment]
Sounds good!

**Comment by poppeman** [comment]
Added for 1.7.0
