### ISSUE TITLE
Errors + exit upon rotating following pan

### ISSUE THREAD

**Issue by Fironet** [poppeman/Pictus#65]
So this one's quite particular. 

Steps to reproduce:

1. Using Pictus 1.6.0 open the test image 1 (below, or any image that is larger than the monitor resolution).
2. Zoom to 100% scale and pan the image to the bottom-left corner (I used the mouse fwiw).
3. Right-click the image and select Orientation>'Rotate 90 degrees' or '270 degrees and flip'.

Result:

The following error message will appear and Pictus will exit. This only occurs with 'Rotate 90 degrees' and '270 degrees and flip', the other orientations aren't affected.

![pictus error message dialog - 1](https://cloud.githubusercontent.com/assets/6971981/17767388/23940852-6573-11e6-8687-19bab523b467.png)

A second, different error will appear if performing the same steps but with an image that doesn't fill the monitor width, only height (for me this occurred with Test image 2 on a 1440p monitor).

![pictus error message dialog - 2](https://cloud.githubusercontent.com/assets/6971981/17767518/a049cfd0-6573-11e6-95e8-ecce2ec81cdc.png)

[Test image 1](https://cloud.githubusercontent.com/assets/6971981/17767591/e3a9b3bc-6573-11e6-9823-39970c151d7a.jpg)

[Test image 2](https://cloud.githubusercontent.com/assets/6971981/17767509/974bd612-6573-11e6-9dbf-093e54896187.png)

**Comment by poppeman** [comment]
It seems that I've already fixed the root cause of that bug in the development version, so rotations should be less broken in the next release.
